// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzwdzyecyukgsggoavlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6d2R6eWVjeXVrZ3NnZ29hdmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTM5MTAsImV4cCI6MjA3Mjg2OTkxMH0.IZCwjD4UF4zYAwxh9OW8IcwkLoV1h9-jejCLOMTVKPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});