
const themes: string[] = [
  'A whimsical fantasy library with floating books',
  'A busy alien marketplace on a desert planet',
  'An underwater city made of coral and bioluminescent plants',
  'A cyberpunk street market at night in the rain',
  'A steam-powered Victorian airship navigating through storm clouds',
  'A secret agent\'s high-tech spy gadget room',
  'A minimalist Japanese zen garden with a koi pond',
  'A medieval castle banquet hall during a grand feast',
  'A robot tending to a garden of glowing, mechanical flowers',
  'The interior of a cozy hobbit hole with a round door and fireplace',

  'A grand, futuristic cityscape with flying vehicles',
  'An enchanted forest with talking animals and giant mushrooms',
  'A haunted Victorian mansion on a spooky, moonlit night',
  'A colorful Dia de los Muertos (Day of the Dead) celebration',
  'A detective\'s messy office in a 1940s film noir setting',
  'A bustling kitchen in a high-end Parisian restaurant',
  'A pirate ship battling a kraken on a stormy sea',
  'An ancient Egyptian tomb filled with treasure and hieroglyphs',
  'A Mad Scientist\'s laboratory with bubbling potions and electrical arcs',
  'A serene scene of cherry blossoms in full bloom in Kyoto, Japan',

  'A vibrant and crowded Mardi Gras parade in New Orleans',
  'A dinosaur-filled jungle from the Cretaceous period',
  'The control room of a massive spaceship exploring a nebula',
  'A post-apocalyptic survivor camp built in the ruins of a city',
  'An opulent ballroom from the Roaring Twenties with flapper dancers',
  'A quiet, snowy village scene in the Swiss Alps',
  'A wizard\'s tower filled with ancient scrolls and magical artifacts',
  'A tranquil scene of hot air balloons floating over Cappadocia, Turkey',
  'A bustling Grand Bazaar in Istanbul with intricate lamps and carpets',
  'A fantasy blacksmith\'s forge with a glowing anvil and epic weapons',

  'A hidden waterfall oasis in a lush tropical jungle',
  'A candy-land world with rivers of chocolate and lollipop trees',
  'A scene from the Wild West with cowboys and a saloon',
  'An ancient, moss-covered treehouse village inhabited by elves',
  'A Viking longship sailing through a fjord',
  'A surreal landscape inspired by Salvador Dali with melting clocks',
  'A high-stakes poker game in a speakeasy',
  'A beautiful Art Nouveau-style conservatory filled with exotic plants',
  'A scene inside a giant, intricate clockwork mechanism',
  'A tranquil monastery perched high in the Himalayan mountains',

  'A magical apothecary shop with floating ingredients and glowing potions',
  'A bustling train station during the golden age of steam locomotives',
  'An arctic research station surrounded by northern lights and ice caves',
  'A vintage carnival at twilight with ferris wheels and cotton candy stands',
  'A samurai dojo at dawn with cherry petals falling through bamboo',
  'An alchemist\'s laboratory hidden beneath a medieval cathedral',
  'A bioluminescent deep-sea ecosystem with giant jellyfish and coral cities',
  'A 1950s diner on Route 66 with classic cars and neon signs',
  'A fairy ring mushroom village with tiny doors and glowing lanterns',
  'An abandoned theme park slowly being reclaimed by nature',
  
  'A grand opera house during a performance with ornate balconies',
  'A nomadic desert camp with colorful tents under a starry sky',
  'A clockmaker\'s workshop filled with intricate timepieces and gears',
  'A hidden grotto with crystalline formations and underground pools',
  'A busy harbor town with tall ships and merchant stalls',
  'A witch\'s cottage in an enchanted swamp with fireflies and moss',
  'A futuristic greenhouse dome on Mars with alien plant life',
  'A cozy mountain cabin during a winter blizzard with warm firelight',
  'An ancient Roman amphitheater during gladiator games',
  'A steampunk inventor\'s airship dock with brass pipes and steam',
  
  'A magical toymaker\'s workshop with animated marionettes and music boxes',
  'A speakeasy hidden behind a bookshelf during Prohibition',
  'An ice palace throne room with frozen waterfalls and crystal chandeliers',
  'A bustling medieval marketplace with jesters, merchants, and livestock',
  'A secret underground bunker from the Cold War era',
  'A tropical tiki bar on a remote island with bamboo furniture',
  'An artist\'s studio in Paris during the Belle Époque period',
  'A mystical observatory tower studying constellations and cosmic phenomena',
  'A vintage barbershop with red leather chairs and striped poles',
  'A fairy tale cottage made entirely of gingerbread and candy',
  
  'A noir detective\'s apartment with venetian blind shadows and cigarette smoke',
  'A bustling spaceport on an alien moon with diverse extraterrestrial species',
  'An ancient library carved into living tree trunks by forest druids',
  'A 1920s jazz club in Harlem with musicians and dancing crowds',
  'A giant\'s kitchen with oversized utensils and enormous meals',
  'A submarine\'s interior navigating through an oceanic trench',
  'A medieval scriptorium with monks illuminating manuscripts',
  'A cybernetic repair shop in a dystopian future city',
  'A haunted carnival funhouse with twisted mirrors and eerie clowns',
  'A traditional Chinese tea house with dragons and paper lanterns',
  
  'A Wild West gold mining camp with prospectors and wooden buildings',
  'An enchanted music conservatory where instruments play themselves',
  'A retro-futuristic space diner from the 1950s vision of tomorrow',
  'A pirate captain\'s quarters filled with maps, treasure, and parrots',
  'A mystical portal nexus connecting multiple fantasy realms',
  'A vintage photography darkroom with red lights and hanging prints',
  'An ancient Mayan temple complex hidden in the jungle canopy',
  'A cozy English pub during a rainy evening with a roaring fire',
  'A mad hatter\'s tea party in a whimsical wonderland setting',
  'A futuristic hydroponic farm in a space station orbiting Earth',

  'A dragon rider\'s aerie nestled high within jagged mountain peaks',
  'A silent movie theater from the 1920s with a live organist and velvet ropes',
  'A celestial forge where a star-smith hammers new constellations into being',
  'A sunken pirate galleon on the ocean floor, teeming with sea life and treasure chests',
  'A Victorian-era ghost hunter\'s study filled with strange devices and blueprints',
  'A bustling intergalactic market on a space station with alien merchants',
  'A tranquil Japanese rock garden with raked sand and carefully placed stones',
  'A wizard\'s tower library with floating books and self-writing quills',
  'A 1970s disco with a sparkling ball, neon dance floor, and mirrored walls',
  'A giant turtle\'s back carrying an entire ecosystem and a small village',

  'A secret agent\'s high-tech lair hidden behind a waterfall',
  'An enchanted blacksmith shop where mythical creatures get their shoes fitted',
  'A post-apocalyptic settlement built inside a massive, rusting rocket',
  'A cozy quilt-making bee in a rustic barn, with patches telling stories',
  'A temple of elements with four chambers for earth, air, fire, and water',
  'A retro video arcade from the 1980s with blinking lights and pixel art',
  'A hermit\'s cave dwelling adorned with ancient cave paintings and artifacts',
  'A royal palace kitchen preparing a grand feast for a hundred guests',
  'A dream weaver\'s workshop where tapestries are made from starlight and memories',
  'A hot air balloon festival at sunrise with dozens of colorful balloons',

  'A mermaid\'s vanity table made from a shipwreck, with pearl combs and mirrors',
  'A frontier trading post on the edge of an unmapped fantasy forest',
  'A cyberpunk noodle bar in a rain-slicked alley of a megacity',
  'An ancient Egyptian tomb, newly opened, with hieroglyphs and artifacts',
  'A whimsical post office where carrier owls and mechanical birds deliver mail',
  'A giant\'s chessboard in a meadow, with living pieces ready to move',
  'A soviet-era cosmonaut training facility with vintage space capsules',
  'A mystical bathhouse for spirits and gods, inspired by Japanese folklore',
  'A detective\'s board filled with clues, red string, and suspect photographs',
  'A treehouse village connected by rope bridges high in the redwood canopy',

  'An artisan bakery in a Parisian backstreet at 4 a.m., preparing the day\'s bread',
  'A throne room of an underwater kingdom made of coral and mother-of-pearl',
  'A vintage suitcase shop with hundreds of stacked trunks and travel stickers',
  'A sacred grove where druids perform rituals under a full moon',
  'A neon-lit cybernetics clinic offering robotic limbs and enhancements',
  'A traditional ryokan (Japanese inn) with tatami mats and a private onsen',
  'A monster truck rally in a muddy arena, with towering vehicles and crowds',
  'A forgotten god\'s shrine being slowly consumed by a massive banyan tree',
  'A 1930s radio broadcast studio with large microphones and sound effect devices',
  'A pocket dimension where the laws of physics are represented by art',

  'A spice merchant\'s stall in a crowded Middle Eastern souk',
  'A secret garden hidden behind a ivy-covered wall, full of rare flowers',
  'A frontier gallows at high noon, with a tense crowd gathered',
  'A celestial navigation school on a cliffside overlooking the ocean',
  'A goblin market where strange and magical trinkets are bartered',
  'A mountaineer\'s base camp on the shoulder of Mount Everest',
  'A surrealist artist\'s studio where paintings are beginning to melt and move',
  'A traditional wooden longhouse in a Viking settlement, preparing for a feast',
  'A zero-gravity sports arena where athletes compete in floating leagues',
  'A quiet fishing pier at the end of the world, where the sea meets the sky',

  'A haunted carnival at midnight, with eerie rides and flickering lights',
  'A futuristic train station with holographic schedules and floating platforms',
  'A medieval alchemist’s laboratory filled with bubbling potions and ancient scrolls',
  'A bustling 19th-century London street market with horse-drawn carriages and street performers',
  'A hidden library in the clouds, accessible only by a ladder made of rainbows',
  'A desert oasis with a crystal-clear pool and palm trees swaying in the breeze',
  'A steampunk airship docked at a floating city, with brass gears and billowing smoke',
  'A lighthouse keeper’s quarters during a storm, with waves crashing against the rocks',
  'A magical candy shop where the sweets glow and change flavor when touched',
  'A samurai dojo at dawn, with cherry blossoms drifting through the training courtyard',

  'A retro diner in the 1950s, with jukeboxes, milkshakes, and chrome booths',
  'A hidden underground city lit by bioluminescent plants and glowing mushrooms',
  'A pirate captain’s quarters on a ship, with treasure maps and a pet parrot',
  'A futuristic farm where robots tend to glowing crops under artificial skies',
  'A medieval tournament ground, with knights jousting and banners fluttering in the wind',
  'A cozy bookshop with a crackling fireplace, towering bookshelves, and a sleeping cat',
  'A floating island in the sky, held aloft by giant balloons and chains',
  'A 1920s speakeasy hidden behind a barbershop, with jazz music and secret passwords',
  'A dragon’s hoard in a volcanic cave, filled with gold, gems, and enchanted artifacts',
  'A futuristic cybernetic workshop where scientists build robotic companions',

  'A tranquil Zen garden with a koi pond, stone lanterns, and a bamboo fence',
  'A haunted castle’s grand ballroom, with ghostly dancers and flickering chandeliers',
  'A bustling spaceport on Mars, with rockets launching and alien travelers',
  'A hidden waterfall cave behind a curtain of water, with ancient carvings on the walls',
  'A 1980s arcade with kids playing classic games like Pac-Man and Space Invaders',
  'A mystical apothecary shop where potions bubble and herbs hang from the ceiling',
  'A royal masquerade ball with elaborate costumes, masks, and a grand staircase',
  'A futuristic cityscape at night, with neon signs, flying cars, and towering skyscrapers',
  'A hidden beach cove with a shipwreck, seashells, and a message in a bottle',
  'A medieval blacksmith’s forge, with sparks flying and swords being crafted',

  'A cozy mountain cabin during a snowstorm, with a roaring fire and warm blankets',
  'A futuristic laboratory where scientists experiment with time travel',
  'A bustling Chinatown street festival with lanterns, dragons, and fireworks',
  'A hidden fairy glade in the forest, with tiny houses and glowing fireflies',
  'A 1960s rock concert with a crowd dancing and a band playing on stage',
  'A futuristic underwater research station with glass domes and deep-sea creatures',
  'A medieval castle’s throne room, with stained glass windows and a king on the throne',
  'A hidden speakeasy in the 1930s, with a secret door and a password to enter',
  'A futuristic shopping mall with holographic displays and floating advertisements',
  'A tranquil tea house in Kyoto, with sliding doors and a view of a bamboo forest',
  
  'A haunted shipwreck on a foggy shore, with ghostly sailors and lost treasure',
  'A futuristic space colony on the Moon, with domed cities and lunar rovers',
  'A medieval village preparing for a festival, with banners, food stalls, and musicians',
  'A hidden garden maze with hedges, fountains, and a secret fountain at the center',
  'A 1970s roller disco with skaters, flashing lights, and a DJ spinning records',
  'A futuristic hospital where robots assist doctors in healing patients',
  'A tranquil lakeside retreat with a wooden dock, canoes, and a sunset view',
  'A haunted asylum with flickering lights, old medical equipment, and ghostly whispers',
  'A futuristic theme park with roller coasters, holographic rides, and robot mascots',
  'A medieval monastery library, with monks copying manuscripts by candlelight'
];

let lastTheme = '';

/**
 * Gets a random theme from the list, ensuring it's not the same as the last one.
 * @returns A random theme string.
 */
export function getRandomTheme(): string {
  if (themes.length === 0) {
    return 'A whimsical fantasy library with floating books'; // Fallback
  }
  if (themes.length === 1) {
    return themes[0];
  }

  let newTheme: string;
  do {
    newTheme = themes[Math.floor(Math.random() * themes.length)];
  } while (newTheme === lastTheme);

  lastTheme = newTheme;
  return newTheme;
}
